import type { Metadata } from "next";
import { Poppins, Sarabun } from "next/font/google";
import "./globals.css";

const poppins = Poppins({
  variable: '--font-poppins',
  weight: ['300', '400', '500', '700'],
  subsets: ["latin"],
});

const sarabun = Sarabun({
  variable: "--font-sarabun",
  weight: ['300', '400', '500', '700'],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "TAKABURGER",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${poppins.variable} ${sarabun.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
